export const countryCodes = [
  { code: '+93', country: '🇦🇫 AFG', label: 'Afganistán' },
  { code: '+355', country: '🇦🇱 ALB', label: 'Albania' },
  { code: '+49', country: '🇩🇪 DEU', label: 'Alemania' },
  { code: '+376', country: '🇦🇩 AND', label: 'Andorra' },
  { code: '+244', country: '🇦🇴 AGO', label: 'Angola' },
  { code: '+1268', country: '🇦🇬 ATG', label: 'Antigua y Barbuda' },
  { code: '+966', country: '🇸🇦 SAU', label: 'Arabia Saudita' },
  { code: '+213', country: '🇩🇿 DZA', label: 'Argelia' },
  { code: '+54', country: '🇦🇷 ARG', label: 'Argentina' },
  { code: '+374', country: '🇦🇲 ARM', label: 'Armenia' },
  { code: '+61', country: '🇦🇺 AUS', label: 'Australia' },
  { code: '+43', country: '🇦🇹 AUT', label: 'Austria' },
  { code: '+994', country: '🇦🇿 AZE', label: 'Azerbaiyán' },
  { code: '+1242', country: '🇧🇸 BHS', label: 'Bahamas' },
  { code: '+880', country: '🇧🇩 BGD', label: 'Bangladés' },
  { code: '+1246', country: '🇧🇧 BRB', label: 'Barbados' },
  { code: '+973', country: '🇧🇭 BHR', label: 'Baréin' },
  { code: '+32', country: '🇧🇪 BEL', label: 'Bélgica' },
  { code: '+501', country: '🇧🇿 BLZ', label: 'Belice' },
  { code: '+229', country: '🇧🇯 BEN', label: 'Benín' },
  { code: '+375', country: '🇧🇾 BLR', label: 'Bielorrusia' },
  { code: '+591', country: '🇧🇴 BOL', label: 'Bolivia' },
  { code: '+387', country: '🇧🇦 BIH', label: 'Bosnia y Herzegovina' },
  { code: '+267', country: '🇧🇼 BWA', label: 'Botsuana' },
  { code: '+55', country: '🇧🇷 BRA', label: 'Brasil' },
  { code: '+673', country: '🇧🇳 BRN', label: 'Brunéi' },
  { code: '+359', country: '🇧🇬 BGR', label: 'Bulgaria' },
  { code: '+226', country: '🇧🇫 BFA', label: 'Burkina Faso' },
  { code: '+257', country: '🇧🇮 BDI', label: 'Burundi' },
  { code: '+975', country: '🇧🇹 BTN', label: 'Bután' },
  { code: '+238', country: '🇨🇻 CPV', label: 'Cabo Verde' },
  { code: '+855', country: '🇰🇭 KHM', label: 'Camboya' },
  { code: '+237', country: '🇨🇲 CMR', label: 'Camerún' },
  { code: '+1', country: '🇨🇦 CAN', label: 'Canadá' },
  { code: '+236', country: '🇨🇫 CAF', label: 'Chad' },
  { code: '+56', country: '🇨🇱 CHL', label: 'Chile' },
  { code: '+86', country: '🇨🇳 CHN', label: 'China' },
  { code: '+357', country: '🇨🇾 CYP', label: 'Chipre' },
  { code: '+57', country: '🇨🇴 COL', label: 'Colombia' },
  { code: '+269', country: '🇰🇲 COM', label: 'Comoras' },
  { code: '+242', country: '🇨🇬 COG', label: 'Congo' },
  { code: '+243', country: '🇨🇩 COD', label: 'Congo (RDC)' },
  { code: '+850', country: '🇰🇵 PRK', label: 'Corea del Norte' },
  { code: '+82', country: '🇰🇷 KOR', label: 'Corea del Sur' },
  { code: '+506', country: '🇨🇷 CRI', label: 'Costa Rica' },
  { code: '+225', country: '🇨🇮 CIV', label: 'Costa de Marfil' },
  { code: '+385', country: '🇭🇷 HRV', label: 'Croacia' },
  { code: '+53', country: '🇨🇺 CUB', label: 'Cuba' },
  { code: '+45', country: '🇩🇰 DNK', label: 'Dinamarca' },
  { code: '+253', country: '🇩🇯 DJI', label: 'Yibuti' },
  { code: '+1767', country: '🇩🇲 DMA', label: 'Dominica' },
  { code: '+593', country: '🇪🇨 ECU', label: 'Ecuador' },
  { code: '+20', country: '🇪🇬 EGY', label: 'Egipto' },
  { code: '+503', country: '🇸🇻 SLV', label: 'El Salvador' },
  { code: '+971', country: '🇦🇪 ARE', label: 'Emiratos Árabes Unidos' },
  { code: '+291', country: '🇪🇷 ERI', label: 'Eritrea' },
  { code: '+421', country: '🇸🇰 SVK', label: 'Eslovaquia' },
  { code: '+386', country: '🇸🇮 SVN', label: 'Eslovenia' },
  { code: '+34', country: '🇪🇸 ESP', label: 'España' },
  { code: '+1', country: '🇺🇸 USA', label: 'Estados Unidos' },
  { code: '+372', country: '🇪🇪 EST', label: 'Estonia' },
  { code: '+251', country: '🇪🇹 ETH', label: 'Etiopía' },
  { code: '+679', country: '🇫🇯 FJI', label: 'Fiyi' },
  { code: '+63', country: '🇵🇭 PHL', label: 'Filipinas' },
  { code: '+358', country: '🇫🇮 FIN', label: 'Finlandia' },
  { code: '+33', country: '🇫🇷 FRA', label: 'Francia' },
  { code: '+241', country: '🇬🇦 GAB', label: 'Gabón' },
  { code: '+220', country: '🇬🇲 GMB', label: 'Gambia' },
  { code: '+995', country: '🇬🇪 GEO', label: 'Georgia' },
  { code: '+233', country: '🇬🇭 GHA', label: 'Ghana' },
  { code: '+30', country: '🇬🇷 GRC', label: 'Grecia' },
  { code: '+1473', country: '🇬🇩 GRD', label: 'Granada' },
  { code: '+502', country: '🇬🇹 GTM', label: 'Guatemala' },
  { code: '+224', country: '🇬🇳 GIN', label: 'Guinea' },
  { code: '+240', country: '🇬🇶 GNQ', label: 'Guinea Ecuatorial' },
  { code: '+245', country: '🇬🇼 GNB', label: 'Guinea-Bisáu' },
  { code: '+592', country: '🇬🇾 GUY', label: 'Guyana' },
  { code: '+509', country: '🇭🇹 HTI', label: 'Haití' },
  { code: '+504', country: '🇭🇳 HND', label: 'Honduras' },
  { code: '+36', country: '🇭🇺 HUN', label: 'Hungría' },
  { code: '+91', country: '🇮🇳 IND', label: 'India' },
  { code: '+62', country: '🇮🇩 IDN', label: 'Indonesia' },
  { code: '+964', country: '🇮🇶 IRQ', label: 'Irak' },
  { code: '+98', country: '🇮🇷 IRN', label: 'Irán' },
  { code: '+353', country: '🇮🇪 IRL', label: 'Irlanda' },
  { code: '+354', country: '🇮🇸 ISL', label: 'Islandia' },
  { code: '+972', country: '🇮🇱 ISR', label: 'Israel' },
  { code: '+39', country: '🇮🇹 ITA', label: 'Italia' },
  { code: '+1876', country: '🇯🇲 JAM', label: 'Jamaica' },
  { code: '+81', country: '🇯🇵 JPN', label: 'Japón' },
  { code: '+962', country: '🇯🇴 JOR', label: 'Jordania' },
  { code: '+7', country: '🇰🇿 KAZ', label: 'Kazajistán' },
  { code: '+254', country: '🇰🇪 KEN', label: 'Kenia' },
  { code: '+996', country: '🇰🇬 KGZ', label: 'Kirguistán' },
  { code: '+686', country: '🇰🇮 KIR', label: 'Kiribati' },
  { code: '+965', country: '🇰🇼 KWT', label: 'Kuwait' },
  { code: '+856', country: '🇱🇦 LAO', label: 'Laos' },
  { code: '+266', country: '🇱🇸 LSO', label: 'Lesoto' },
  { code: '+371', country: '🇱🇻 LVA', label: 'Letonia' },
  { code: '+961', country: '🇱🇧 LBN', label: 'Líbano' },
  { code: '+231', country: '🇱🇷 LBR', label: 'Liberia' },
  { code: '+218', country: '🇱🇾 LBY', label: 'Libia' },
  { code: '+423', country: '🇱🇮 LIE', label: 'Liechtenstein' },
  { code: '+370', country: '🇱🇹 LTU', label: 'Lituania' },
  { code: '+352', country: '🇱🇺 LUX', label: 'Luxemburgo' },
  { code: '+389', country: '🇲🇰 MKD', label: 'Macedonia del Norte' },
  { code: '+261', country: '🇲🇬 MDG', label: 'Madagascar' },
  { code: '+60', country: '🇲🇾 MYS', label: 'Malasia' },
  { code: '+265', country: '🇲🇼 MWI', label: 'Malaui' },
  { code: '+960', country: '🇲🇻 MDV', label: 'Maldivas' },
  { code: '+223', country: '🇲🇱 MLI', label: 'Malí' },
  { code: '+356', country: '🇲🇹 MLT', label: 'Malta' },
  { code: '+212', country: '🇲🇦 MAR', label: 'Marruecos' },
  { code: '+230', country: '🇲🇺 MUS', label: 'Mauricio' },
  { code: '+222', country: '🇲🇷 MRT', label: 'Mauritania' },
  { code: '+52', country: '🇲🇽 MEX', label: 'México' },
  { code: '+691', country: '🇫🇲 FSM', label: 'Micronesia' },
  { code: '+373', country: '🇲🇩 MDA', label: 'Moldavia' },
  { code: '+377', country: '🇲🇨 MCO', label: 'Mónaco' },
  { code: '+976', country: '🇲🇳 MNG', label: 'Mongolia' },
  { code: '+382', country: '🇲🇪 MNE', label: 'Montenegro' },
  { code: '+258', country: '🇲🇿 MOZ', label: 'Mozambique' },
  { code: '+95', country: '🇲🇲 MMR', label: 'Myanmar' },
  { code: '+264', country: '🇳🇦 NAM', label: 'Namibia' },
  { code: '+674', country: '🇳🇷 NRU', label: 'Nauru' },
  { code: '+977', country: '🇳🇵 NPL', label: 'Nepal' },
  { code: '+505', country: '🇳🇮 NIC', label: 'Nicaragua' },
  { code: '+227', country: '🇳🇪 NER', label: 'Níger' },
  { code: '+234', country: '🇳🇬 NGA', label: 'Nigeria' },
  { code: '+47', country: '🇳🇴 NOR', label: 'Noruega' },
  { code: '+64', country: '🇳🇿 NZL', label: 'Nueva Zelanda' },
  { code: '+968', country: '🇴🇲 OMN', label: 'Omán' },
  { code: '+31', country: '🇳🇱 NLD', label: 'Países Bajos' },
  { code: '+92', country: '🇵🇰 PAK', label: 'Pakistán' },
  { code: '+680', country: '🇵🇼 PLW', label: 'Palaos' },
  { code: '+507', country: '🇵🇦 PAN', label: 'Panamá' },
  { code: '+675', country: '🇵🇬 PNG', label: 'Papúa Nueva Guinea' },
  { code: '+595', country: '🇵🇾 PRY', label: 'Paraguay' },
  { code: '+51', country: '🇵🇪 PER', label: 'Perú' },
  { code: '+48', country: '🇵🇱 POL', label: 'Polonia' },
  { code: '+351', country: '🇵🇹 PRT', label: 'Portugal' },
  { code: '+1', country: '🇵🇷 PRI', label: 'Puerto Rico' },
  { code: '+974', country: '🇶🇦 QAT', label: 'Catar' },
  { code: '+44', country: '🇬🇧 GBR', label: 'Reino Unido' },
  { code: '+236', country: '🇨🇫 CAF', label: 'República Centroafricana' },
  { code: '+420', country: '🇨🇿 CZE', label: 'República Checa' },
  { code: '+1809', country: '🇩🇴 DOM', label: 'República Dominicana' },
  { code: '+250', country: '🇷🇼 RWA', label: 'Ruanda' },
  { code: '+40', country: '🇷🇴 ROU', label: 'Rumanía' },
  { code: '+7', country: '🇷🇺 RUS', label: 'Rusia' },
  { code: '+685', country: '🇼🇸 WSM', label: 'Samoa' },
  { code: '+378', country: '🇸🇲 SMR', label: 'San Marino' },
  { code: '+1869', country: '🇰🇳 KNA', label: 'San Cristóbal y Nieves' },
  { code: '+1758', country: '🇱🇨 LCA', label: 'Santa Lucía' },
  { code: '+1784', country: '🇻🇨 VCT', label: 'San Vicente y Granadinas' },
  { code: '+239', country: '🇸🇹 STP', label: 'Santo Tomé y Príncipe' },
  { code: '+221', country: '🇸🇳 SEN', label: 'Senegal' },
  { code: '+381', country: '🇷🇸 SRB', label: 'Serbia' },
  { code: '+248', country: '🇸🇨 SYC', label: 'Seychelles' },
  { code: '+232', country: '🇸🇱 SLE', label: 'Sierra Leona' },
  { code: '+65', country: '🇸🇬 SGP', label: 'Singapur' },
  { code: '+963', country: '🇸🇾 SYR', label: 'Siria' },
  { code: '+252', country: '🇸🇴 SOM', label: 'Somalia' },
  { code: '+94', country: '🇱🇰 LKA', label: 'Sri Lanka' },
  { code: '+268', country: '🇸🇿 SWZ', label: 'Suazilandia' },
  { code: '+27', country: '🇿🇦 ZAF', label: 'Sudáfrica' },
  { code: '+249', country: '🇸🇩 SDN', label: 'Sudán' },
  { code: '+211', country: '🇸🇸 SSD', label: 'Sudán del Sur' },
  { code: '+46', country: '🇸🇪 SWE', label: 'Suecia' },
  { code: '+41', country: '🇨🇭 CHE', label: 'Suiza' },
  { code: '+597', country: '🇸🇷 SUR', label: 'Surinam' },
  { code: '+66', country: '🇹🇭 THA', label: 'Tailandia' },
  { code: '+255', country: '🇹🇿 TZA', label: 'Tanzania' },
  { code: '+992', country: '🇹🇯 TJK', label: 'Tayikistán' },
  { code: '+670', country: '🇹🇱 TLS', label: 'Timor Oriental' },
  { code: '+228', country: '🇹🇬 TGO', label: 'Togo' },
  { code: '+676', country: '🇹🇴 TON', label: 'Tonga' },
  { code: '+1868', country: '🇹🇹 TTO', label: 'Trinidad y Tobago' },
  { code: '+216', country: '🇹🇳 TUN', label: 'Túnez' },
  { code: '+993', country: '🇹🇲 TKM', label: 'Turkmenistán' },
  { code: '+90', country: '🇹🇷 TUR', label: 'Turquía' },
  { code: '+688', country: '🇹🇻 TUV', label: 'Tuvalu' },
  { code: '+380', country: '🇺🇦 UKR', label: 'Ucrania' },
  { code: '+256', country: '🇺🇬 UGA', label: 'Uganda' },
  { code: '+598', country: '🇺🇾 URY', label: 'Uruguay' },
  { code: '+998', country: '🇺🇿 UZB', label: 'Uzbekistán' },
  { code: '+678', country: '🇻🇺 VUT', label: 'Vanuatu' },
  { code: '+58', country: '🇻🇪 VEN', label: 'Venezuela' },
  { code: '+84', country: '🇻🇳 VNM', label: 'Vietnam' },
  { code: '+967', country: '🇾🇪 YEM', label: 'Yemen' },
  { code: '+260', country: '🇿🇲 ZMB', label: 'Zambia' },
  { code: '+263', country: '🇿🇼 ZWE', label: 'Zimbabue' },
];
